#!/usr/bin/env python3
"""
desktop.py — Native Windows desktop app using pywebview.

Starts the FastAPI backend on a random free port and opens a native
OS window (Win32 on Windows, Cocoa on macOS, GTK on Linux) rendering
the same HTML UI. No browser needed. Packages to a single .exe with
PyInstaller.

Usage:
    python desktop.py              # launch desktop window
    python desktop.py --port 8765  # fixed port (useful for debugging)

Build to .exe (Windows):
    pip install pyinstaller pywebview
    pyinstaller desktop.spec       # see desktop.spec generated by --generate-spec
    # or quick one-liner:
    pyinstaller --onefile --windowed --name "CodingAssistant" --icon ui/icon.ico desktop.py
"""
from __future__ import annotations

import argparse
import socket
import sys
import threading
import time
from pathlib import Path


def _free_port() -> int:
    """Find a free TCP port."""
    with socket.socket() as s:
        s.bind(("127.0.0.1", 0))
        return s.getsockname()[1]


def _start_server(port: int) -> None:
    """Run uvicorn in a background daemon thread."""
    import uvicorn

    # When frozen by PyInstaller, sys._MEIPASS is the temp extraction dir
    if getattr(sys, "frozen", False):
        base = Path(sys._MEIPASS)  # type: ignore
        sys.path.insert(0, str(base))

    uvicorn.run(
        "api:app",
        host="127.0.0.1",
        port=port,
        log_level="warning",   # quiet in production
        access_log=False,
    )


def _wait_for_server(port: int, timeout: float = 15.0) -> bool:
    """Poll until the server is accepting connections."""
    deadline = time.time() + timeout
    while time.time() < deadline:
        try:
            with socket.create_connection(("127.0.0.1", port), timeout=0.5):
                return True
        except OSError:
            time.sleep(0.1)
    return False


def main() -> None:
    parser = argparse.ArgumentParser(description="Coding Assistant Desktop")
    parser.add_argument("--port", type=int, default=0,
                        help="Port for the embedded server (0 = random free port)")
    parser.add_argument("--debug", action="store_true",
                        help="Open browser devtools alongside the window")
    args = parser.parse_args()

    port = args.port or _free_port()

    # Start backend in a daemon thread (dies when the window closes)
    server_thread = threading.Thread(target=_start_server, args=(port,), daemon=True)
    server_thread.start()

    # Wait for it to be ready before opening the window
    print(f"Starting Coding Assistant on port {port}...")
    if not _wait_for_server(port, timeout=20.0):
        print("ERROR: backend failed to start within 20 seconds.", file=sys.stderr)
        sys.exit(1)

    url = f"http://127.0.0.1:{port}"

    try:
        import webview  # type: ignore  (pywebview)
    except ImportError:
        print(
            "pywebview is not installed.\n"
            "Install it with:  pip install pywebview\n"
            f"Then open {url} in your browser as a fallback.",
            file=sys.stderr,
        )
        # Fallback: open in system browser
        import webbrowser
        webbrowser.open(url)
        # Keep server alive until user presses Ctrl-C
        try:
            print(f"Server running at {url}  (press Ctrl-C to quit)")
            threading.Event().wait()
        except KeyboardInterrupt:
            pass
        return

    window = webview.create_window(
        title="Coding Assistant",
        url=url,
        width=1280,
        height=860,
        min_size=(900, 600),
        text_select=True,        # allow copying code from the UI
        confirm_close=False,
    )

    webview.start(
        debug=args.debug,
        # On Windows this uses the Edge WebView2 runtime (ships with Windows 11,
        # installable on Windows 10). Falls back to MSHTML if unavailable.
        gui="edgechromium",      # best rendering on Windows
        # gui="cef"              # alternative: Chromium Embedded Framework
    )


if __name__ == "__main__":
    main()
